application: kmujournal
threadsafe: true
runtime: python27
api_version: 1

handlers:
- url: /.*
  script: run.py

libraries:
- name: beautifulSoup4
  version: "4.6.0"
- name: BeautifulSoup
  version: "3.2.1"
- name: bs4
  version: "0.0.1"
- name: click
  version: "6.7"
- name: Flask-SQLAlchemy
  version: "2.2"
- name: Flask
  version: "0.12.1"
- name: Jinja2
  version: "2.9.6"
- name: request
  version: "0.0.0"
- name: SQLAlchemy
  version: "1.1.9"
- name: Werkzeug
  version: "0.12.1"
- name: MarkupSafe
  version: "1.0"
- name: packaging
  version: "16.8"
- name: pyparsing
  version: "2.2.0"
